import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

export default function (pi: ExtensionAPI) {
  let enabled = true; // default: ON

  const TASK_SPLIT_INSTRUCTIONS = `
TASK SPLITTING RULES (STRICT):

When a user request involves any of the following, you MUST split it into smaller steps instead of doing everything in one shot:
- Writing or overwriting a large file (> ~100 lines).
- Editing multiple locations across several files.
- Performing many related tool calls at once (e.g., many writes/edits/bashes).

REQUIRED BEHAVIOR:
- First, briefly estimate the size of the task (short note is enough).
- If it’s small (< ~100 lines total change), you may do it in one go.
- If medium or large:
  - Break it into clear subtasks (3–8 steps typical).
  - Print a short numbered plan to the user before starting implementation.
  - Execute step by step, one at a time.
  - After each step, add a very brief confirmation line (1–2 lines) before moving on.
- Never attempt to rewrite or edit an entire large file in a single operation if it risks timeout or context overflow.
- Prefer:
  - Smaller, incremental edits over huge rewrites.
  - Splitting long operations into multiple focused tool calls instead of one giant call.

Use the split_task tool when you detect a medium/big task so your plan is explicit and consistent.
`;

  // Notify on session start so user knows it's active
  pi.on("session_start", async (_event, ctx) => {
    if (!enabled) return;
    ctx.ui.notify("Task Splitting: ON (use /task-split to control)", "info");
  });

  // Inject task-split instructions when enabled
  pi.on("before_agent_start", async (event, _ctx) => {
    if (!enabled) return event;
    const base = event.systemPrompt || "";
    return {
      systemPrompt: base + TASK_SPLIT_INSTRUCTIONS,
    };
  });

  // Tool for the agent to explicitly split a task into subtasks
  pi.registerTool({
    name: "split_task",
    label: "Split Task",
    description:
      "Use this tool when facing a medium or large task that should be broken into smaller, sequential steps. Call it early with a short description of the overall work; it will return a concrete step-by-step plan you must follow.",
    promptSnippet:
      "split_task: break large tasks into small, ordered steps before implementation",
    promptGuidelines: [
      "Use split_task when the task involves many changes across files or very long writes/edits. Call it BEFORE doing heavy work."
    ],
    parameters: Type.Object({
      description: Type.String({
        description:
          "Short description of the overall task (1–3 sentences).",
      }),
    }),
    async execute(_toolCallId, params) {
      const desc = (params.description || "").trim();

      if (!desc) {
        return {
          content: [
            {
              type: "text",
              text: "Error: description is required. Provide a short summary of the task.",
            },
          ],
          details: {},
        };
      }

      const plan = `
TASK SPLIT PLAN (generated by split_task):

Based on this task: "${desc}"

Steps:
1) Analyze and confirm scope:
   - Read relevant files/configs.
   - Briefly summarize what needs to change.

2) Design the solution:
   - Outline concrete changes (files, components, logic).
   - Identify dependencies between steps.

3) Implement in small chunks:
   - Each step should be limited and focused.
   - Confirm completion of each step before moving on.

4) Validate incrementally:
   - After each meaningful change, run quick checks (lint/build/test/startup as appropriate).
   - Fix issues immediately instead of accumulating them.

5) Final review:
   - Ensure all parts work together.
   - Clean up temporary/debug code and comments.

RULES:
- Do NOT try to do everything in one tool call or message.
- If a step looks too big, split it further.
`;

      return {
        content: [{ type: "text", text: plan.trim() }],
        details: {},
      };
    },
  });

  // Command: /task-split on|off|toggle|status
  pi.registerCommand("task-split", {
    description:
      "Control task splitting for big write/edit operations (on/off/toggle/status)",
    handler: async (args, ctx) => {
      const arg = (args || "").trim().toLowerCase();

      if (arg === "off") {
        enabled = false;
        ctx.ui.notify("Task splitting: OFF", "info");
        return;
      }

      if (arg === "on") {
        enabled = true;
        ctx.ui.notify("Task splitting: ON", "info");
        return;
      }

      if (arg === "toggle") {
        enabled = !enabled;
        ctx.ui.notify(`Task splitting: ${enabled ? "ON" : "OFF"}`, "info");
        return;
      }

      // default or 'status'
      ctx.ui.notify(
        `Task splitting is currently: ${enabled ? "ON" : "OFF"}`,
        "info",
      );
    },
  });
}
